# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

front.cart.index:
    path: /cart
    defaults:
        _controller: 'cart.controller.front:indexAction'
    options:
        breadcrumb:
            label: order.heading.cart

front.cart.add:
    path: '/cart/add/{id},{variant},{quantity}'
    defaults:
        _controller: 'cart.controller.front:addAction'
        variant: 'null'
        quantity: '1'
    options:
        expose: true

front.cart.edit:
    path: '/cart/edit/{id},{quantity}'
    defaults:
        _controller: 'cart.controller.front:editAction'
    options:
        expose: true

front.cart.delete:
    path: '/cart/delete/{id}'
    defaults:
        _controller: 'cart.controller.front:deleteAction'
    options:
        expose: true

front.address.index:
    path: /address
    defaults:
        _controller: 'address.controller.front:indexAction'
    options:
        expose: true
        breadcrumb:
            label: order.heading.address

front.confirm.index:
    path: /confirm
    defaults:
        _controller: 'confirmation.controller.front:indexAction'
    options:
        breadcrumb:
            label: order.heading.confirm
