# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

services:
    news.layout_box.configurator:
        class: WellCommerce\Bundle\CmsBundle\Service\Layout\Configurator\NewsBoxConfigurator
        autowire: true
        tags:
            - { name: layout_box.configurator }

    news_feed.layout_box.configurator:
        class: WellCommerce\Bundle\CmsBundle\Service\Layout\Configurator\NewsFeedBoxConfigurator
        autowire: true
        tags:
            - { name: layout_box.configurator }

    news.controller.box:
        class: WellCommerce\Bundle\CmsBundle\Controller\Box\NewsBoxController
        arguments: ['@news.manager']
        calls:
            - [setContainer, ['@service_container']]

    news_feed.controller.box:
        class: WellCommerce\Bundle\CmsBundle\Controller\Box\NewsFeedBoxController
        arguments: ['@news.manager']
        calls:
            - [setContainer, ['@service_container']]

    news.controller.front:
        class: WellCommerce\Bundle\CmsBundle\Controller\Front\NewsController
        arguments: ['@news.manager']
        calls:
            - [setContainer, ['@service_container']]

    twig.extension.news:
        class: WellCommerce\Bundle\CmsBundle\Twig\NewsExtension
        arguments: ['@news.dataset.front']
        tags:
            - { name: twig.extension }

    news.request.storage:
        class: WellCommerce\Bundle\CmsBundle\Request\NewsRequestStorage

    news_feed.provider:
        class: WellCommerce\Bundle\CmsBundle\Service\Feed\NewsFeedProvider
        calls:
            - [setContainer, ['@service_container']]
