# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

admin.feature.index:
    path: /index
    defaults:
        _controller: 'feature.controller.admin:indexAction'
    options:
        require_admin_permission: feature.index

admin.feature.grid:
    path: /grid
    condition: "request.isXmlHttpRequest()"
    defaults:
        _controller: 'feature.controller.admin:gridAction'
    options:
        expose: true
        require_admin_permission: attribute_value.index

admin.feature.add:
    path: /add
    defaults:
        _controller: 'feature.controller.admin:addAction'
    options:
        require_admin_permission: feature.add

admin.feature.edit:
    path: '/edit/{id}'
    defaults:
        _controller: 'feature.controller.admin:editAction'
    options:
        expose: true
        require_admin_permission: feature.edit

admin.feature.delete:
    path: '/delete/{id}'
    defaults:
        _controller: 'feature.controller.admin:deleteAction'
    options:
        expose: true
        require_admin_permission: feature.delete

admin.feature.delete_group:
    path: '/delete_group'
    defaults:
        _controller: 'feature.controller.admin:deleteGroupAction'
    options:
        expose: true
        require_admin_permission: feature.delete

