# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

services:
    producer_menu.layout_box.configurator:
        class: WellCommerce\Bundle\CatalogBundle\Service\Layout\Configurator\ProducerMenuBoxConfigurator
        arguments: ['@producer_menu.layout_box.controller', '@producer.dataset.admin']
        tags:
            - { name: layout_box.configurator }

    producer_menu.layout_box.controller:
        class: WellCommerce\Bundle\CatalogBundle\Controller\Box\ProducerMenuBoxController
        arguments: ['@producer.manager']
        calls:
            - [setContainer, ['@service_container']]

    producer_products.layout_box.configurator:
        class: WellCommerce\Bundle\CatalogBundle\Service\Layout\Configurator\ProducerProductsBoxConfigurator
        autowire: true
        tags:
            - { name: layout_box.configurator }

    producer_products.layout_box.controller:
        class: WellCommerce\Bundle\CatalogBundle\Controller\Box\ProducerProductsBoxController
        arguments: ['@producer.manager']
        calls:
            - [setContainer, ['@service_container']]

    producer.controller.front:
        class: WellCommerce\Bundle\CatalogBundle\Controller\Front\ProducerController
        arguments: ['@producer.manager']
        calls:
            - [setContainer, ['@service_container']]

    producer.storage:
        class: WellCommerce\Bundle\CatalogBundle\Request\Storage\ProducerStorage

    twig.extension.producer:
        class: WellCommerce\Bundle\CatalogBundle\Twig\Extension\ProducerExtension
        tags:
            - { name: twig.extension }
        arguments: ['@producer.dataset.front']

