# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

services:
    product_status.layout_box.configurator:
        class: WellCommerce\Bundle\CatalogBundle\Service\Layout\Configurator\ProductStatusBoxConfigurator
        autowire: true
        tags:
            - { name: layout_box.configurator }

    product_status.storage:
        class: WellCommerce\Bundle\CatalogBundle\Request\Storage\ProductStatusStorage

    product_status.transformer:
        class: WellCommerce\Bundle\CatalogBundle\DataSet\Transformer\ProductStatusTransformer
        tags:
            - { name: dataset.transformer, alias: product_status }

    twig.extension.product_status:
        class: WellCommerce\Bundle\CatalogBundle\Twig\Extension\ProductStatusExtension
        tags:
            - { name: twig.extension }
        arguments: ['@product_status.dataset.front', '@product_status.repository']

    product_status.controller.front:
        class: WellCommerce\Bundle\CatalogBundle\Controller\Front\ProductStatusController
        arguments: ['@product_status.manager']
        calls:
            - [setContainer, ['@service_container']]

    product_status.layout_box.controller:
        class: WellCommerce\Bundle\CatalogBundle\Controller\Box\ProductStatusBoxController
        arguments: ['@product_status.manager']
        calls:
            - [setContainer, ['@service_container']]
