# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

admin.page.index:
    path: /index
    defaults:
        _controller: 'page.controller.admin:indexAction'
    options:
        require_admin_permission: page.index

admin.page.grid:
    path: /grid
    condition: "request.isXmlHttpRequest()"
    defaults:
        _controller: 'page.controller.admin:gridAction'
    options:
        expose: true
        require_admin_permission: page.index

admin.page.add:
    path: /add
    defaults:
        _controller: 'page.controller.admin:addAction'
    options:
        require_admin_permission: page.add

admin.page.edit:
    path: '/edit/{id}'
    defaults:
        _controller: 'page.controller.admin:editAction'
    options:
        expose: true
        require_admin_permission: page.edit

admin.page.delete:
    path: '/delete/{id}'
    defaults:
        _controller: 'page.controller.admin:deleteAction'
    options:
        expose: true
        require_admin_permission: page.delete

admin.page.delete_group:
    path: '/delete_group'
    defaults:
        _controller: 'page.controller.admin:deleteGroupAction'
    options:
        expose: true
        require_admin_permission: page.delete

admin.page.edit_layout:
    path: '/edit/layout/{id}'
    defaults:
        _controller: 'page.controller.admin:editLayoutAction'
    options:
        expose: true
        require_admin_permission: page.edit

admin.page.save_layout:
    path: '/edit/layout/save/{id}'
    defaults:
        _controller: 'page.controller.admin:saveLayoutAction'
    options:
        expose: true
        require_admin_permission: page.edit
