# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

admin.deliverer.index:
    path: /index
    defaults:
        _controller: 'deliverer.controller.admin:indexAction'
    options:
        require_admin_permission: deliverer.index

admin.deliverer.grid:
    path: /grid
    condition: "request.isXmlHttpRequest()"
    defaults:
        _controller: 'deliverer.controller.admin:gridAction'
    options:
        expose: true
        require_admin_permission: deliverer.index

admin.deliverer.add:
    path: /add
    defaults:
        _controller: 'deliverer.controller.admin:addAction'
    options:
        require_admin_permission: deliverer.add

admin.deliverer.edit:
    path: '/edit/{id}'
    defaults:
        _controller: 'deliverer.controller.admin:editAction'
    options:
        expose: true
        require_admin_permission: deliverer.edit

admin.deliverer.delete:
    path: '/delete/{id}'
    defaults:
        _controller: 'deliverer.controller.admin:deleteAction'
    options:
        expose: true
        require_admin_permission: deliverer.delete

admin.deliverer.delete_group:
    path: '/delete_group'
    defaults:
        _controller: 'deliverer.controller.admin:deleteGroupAction'
    options:
        expose: true
        require_admin_permission: deliverer.delete
