# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

services:
    layout_box.renderer:
        class: WellCommerce\Component\Layout\Renderer\LayoutBoxRenderer
        autowire: true

    layout_box.configurator.collection:
        class: WellCommerce\Component\Layout\Configurator\LayoutBoxConfiguratorCollection
