# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

services:
    route.controller:
        class: WellCommerce\Bundle\CoreBundle\Controller\RouteController
        arguments: ["@slug.generator"]

    routable.subscriber:
        class: WellCommerce\Bundle\CoreBundle\Doctrine\EventSubscriber\RoutableSubscriber
        arguments: ['%routing_discriminator_map%']
        tags:
            - { name: doctrine.event_subscriber }

    dataset.transformer.route:
        class: WellCommerce\Bundle\CoreBundle\DataSet\Transformer\RouteTransformer
        tags:
            - { name: dataset.transformer, alias: route }
        arguments: ['@routing.generator']

    routing.orm.validator.unique:
        class: WellCommerce\Bundle\CoreBundle\Validator\UniqueRouteValidator
        arguments: ['@route.repository', '@router.helper']
        tags:
            - { name: validator.constraint_validator, alias: routing.orm.validator.unique }

    routing.provider:
        class: WellCommerce\Bundle\CoreBundle\Provider\RouteProvider
        arguments: ['%routing_generator_map%', '@route.repository']

    routing.chain_router:
        class: Symfony\Cmf\Component\Routing\ChainRouter
        arguments: ['@logger']
        calls:
            - [setContext, ['@router.request_context']]

    routing.nested_matcher:
        class: Symfony\Cmf\Component\Routing\NestedMatcher\NestedMatcher
        arguments: ['@routing.provider', '@routing.final_matcher']

    routing.matcher.dummy_collection:
        class: Symfony\Component\Routing\RouteCollection
        public: false

    routing.matcher.dummy_context:
        class: Symfony\Component\Routing\RequestContext
        public: false

    routing.final_matcher:
        class: Symfony\Cmf\Component\Routing\NestedMatcher\UrlMatcher
        arguments: ['@routing.matcher.dummy_collection', '@routing.matcher.dummy_context']

    routing.dynamic_router:
        class: Symfony\Cmf\Component\Routing\DynamicRouter
        arguments: ['@router.request_context', '@routing.nested_matcher', '@routing.generator', null, '@?event_dispatcher', '@routing.provider']

    routing.generator:
        class: Symfony\Cmf\Component\Routing\ProviderBasedGenerator
        arguments: ['@routing.provider', '@?logger']

    slug.generator:
        class: WellCommerce\Bundle\CoreBundle\Generator\SlugGenerator
        arguments: ['@route.repository']

    router.helper:
        class: WellCommerce\Bundle\CoreBundle\Helper\Router\RouterHelper
        arguments: ['@router', '@request.helper']

    twig.extension.dynamic_routing:
        class: WellCommerce\Bundle\CoreBundle\Twig\DynamicRoutingExtension
        arguments: ['@router', '@request.helper']
        tags:
            - { name: twig.extension }
