
services:
    coupon.controller.front:
        class: WellCommerce\Bundle\CouponBundle\Controller\Front\CouponController
        arguments: ['@order.manager']
        calls:
            - [setContainer, ['@service_container']]

    coupon.request_param_converter:
        class: WellCommerce\Bundle\CouponBundle\Request\ParamConverter\CouponParamConverter
        tags:
            - { name: request.param_converter, converter: category, priority: 0 }
        arguments: ['@coupon.repository', code, [WellCommerce\Bundle\CouponBundle\Entity\Coupon]]

    coupon.checker:
        class: WellCommerce\Bundle\CouponBundle\Checker\CouponChecker
        arguments: ['@order.provider.front', '@order.repository', '@currency.helper']

    coupon.order.visitor:
        class: WellCommerce\Bundle\CouponBundle\Visitor\CouponOrderVisitor
        tags:
            - { name: order.visitor, alias: coupon }
        arguments: ['@order.modifier.provider', '@currency.helper']

    coupon_discount.order.modifier.configurator:
        class: WellCommerce\Bundle\OrderBundle\Configurator\OrderModifierConfigurator
        arguments: { name: coupon_discount, description: order.label.coupon_discount, subtraction: true, hierarchy: 100 }

    coupon_discount.order.modifier:
        class: WellCommerce\Bundle\OrderBundle\Entity\OrderModifier
        factory: ['@order_modifier.factory', create]
        configurator: ['@coupon_discount.order.modifier.configurator', configure]
        tags:
            - { name: order.modifier, alias: coupon_discount }
