WellCommerce\Bundle\AppBundle\Entity\Company:
    fields:
        id:
            groups:
                - default
                - company
        name:
            groups:
                - default
                - company
        shortName:
            groups:
                - default
                - company
        line1:
            groups:
                - default
                - company
        line2:
            groups:
                - default
                - company
        postalCode:
            groups:
                - default
                - company
        state:
            groups:
                - default
                - company
        city:
            groups:
                - default
                - company
        country:
            groups:
                - default
                - company
