# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

admin.dictionary.index:
    path: /index
    defaults:
        _controller: 'dictionary.controller.admin:indexAction'
    options:
        expose: true
        require_admin_permission: dictionary.index

admin.dictionary.grid:
    path: /grid
    condition: "request.isXmlHttpRequest()"
    defaults:
        _controller: 'dictionary.controller.admin:gridAction'
    options:
        expose: true
        require_admin_permission: dictionary.index

admin.dictionary.add:
    path: /add
    defaults:
        _controller: 'dictionary.controller.admin:addAction'
    options:
        expose: true
        require_admin_permission: dictionary.add

admin.dictionary.edit:
    path: '/edit/{id}'
    defaults:
        _controller: 'dictionary.controller.admin:editAction'
    options:
        expose: true
        require_admin_permission: dictionary.edit

admin.dictionary.sync:
    path: /sync
    defaults:
        _controller: 'dictionary.controller.admin:syncAction'
    options:
        expose: true
        require_admin_permission: dictionary.edit

admin.dictionary.delete:
    path: '/delete/{id}'
    defaults:
        _controller: 'dictionary.controller.admin:deleteAction'
    options:
        expose: true
        require_admin_permission: dictionary.delete

admin.dictionary.delete_group:
    path: '/delete_group'
    defaults:
        _controller: 'dictionary.controller.admin:deleteGroupAction'
    options:
        expose: true
        require_admin_permission: dictionary.delete
