# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

WellCommerce\Bundle\FeatureBundle\Entity\ProductFeature:
    type: entity
    table: product_feature
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        value:
            type: text
            nullable: false
    manyToOne:
        product:
            targetEntity: WellCommerce\Bundle\CatalogBundle\Entity\Product
            fetch: LAZY
            inversedBy: features
            joinColumns:
                product_id:
                    referencedColumnName: id
                    onDelete: CASCADE
        feature:
            targetEntity: WellCommerce\Bundle\FeatureBundle\Entity\Feature
            fetch: LAZY
            joinColumns:
                feature_id:
                    referencedColumnName: id
                    onDelete: CASCADE
