WellCommerce\Bundle\OrderBundle\Entity\OrderStatusHistory:
    type: entity
    table: orders_status_history
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        notify:
            type: boolean
            nullable: false
        comment:
            type: string
            length: 1000
            nullable: false
    manyToOne:
        order:
            targetEntity: WellCommerce\Bundle\OrderBundle\Entity\Order
            fetch: LAZY
            inversedBy: orderStatusHistory
            joinColumns:
                order_id:
                    referencedColumnName: id
                    onDelete: CASCADE
        orderStatus:
            targetEntity: WellCommerce\Bundle\OrderBundle\Entity\OrderStatus
            fetch: LAZY
            joinColumns:
                order_status_id:
                    referencedColumnName: id
                    onDelete: RESTRICT
