WellCommerce\Bundle\OrderBundle\Entity\OrderStatusGroup:
    type: entity
    table: order_status_group
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
