WellCommerce\Bundle\OrderBundle\Entity\PaymentMethod:
    type: entity
    table: payment_method
    repositoryClass: WellCommerce\Bundle\OrderBundle\Repository\PaymentMethodRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        processor:
            type: string
            length: 64
            nullable: false
        configuration:
            type: json_array
    manyToOne:
        paymentPendingOrderStatus:
            targetEntity: WellCommerce\Bundle\OrderBundle\Entity\OrderStatus
            fetch: LAZY
            joinColumns:
                payment_pending_order_status_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
        paymentSuccessOrderStatus:
            targetEntity: WellCommerce\Bundle\OrderBundle\Entity\OrderStatus
            fetch: LAZY
            joinColumns:
                payment_success_order_status_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
        paymentFailureOrderStatus:
            targetEntity: WellCommerce\Bundle\OrderBundle\Entity\OrderStatus
            fetch: LAZY
            joinColumns:
                payment_failure_order_status_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
    manyToMany:
        clientGroups:
            targetEntity: WellCommerce\Bundle\AppBundle\Entity\ClientGroup
            fetch: LAZY
            joinTable:
                name: payment_method_client_group
                joinColumns:
                    -
                        name: payment_method_id
                        onDelete: CASCADE
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: client_group_id
                        onDelete: CASCADE
                        referencedColumnName: id
        shippingMethods:
            targetEntity: WellCommerce\Bundle\OrderBundle\Entity\ShippingMethod
            fetch: LAZY
            inversedBy: paymentMethods
            joinTable:
                name: payment_method_shipping_method
                joinColumns:
                    -
                        name: payment_method_id
                        nullable: false
                        onDelete: CASCADE
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: shipping_method_id
                        nullable: false
                        onDelete: CASCADE
                        referencedColumnName: id
