WellCommerce\Bundle\CatalogBundle\Entity\ProductPhoto:
    type: entity
    table: product_photo
    cache:
        usage: NONSTRICT_READ_WRITE
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        mainPhoto:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            options:
                default: 0
            column: main_photo
    manyToOne:
        photo:
            targetEntity: WellCommerce\Bundle\AppBundle\Entity\Media
            fetch: LAZY
            joinColumns:
                photo_id:
                    referencedColumnName: id
        product:
            targetEntity: WellCommerce\Bundle\CatalogBundle\Entity\Product
            fetch: LAZY
            mappedBy: null
            inversedBy: productPhotos
            joinColumns:
                product_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
