WellCommerce\Bundle\CatalogBundle\Entity\VariantOption:
    type: entity
    table: variant_option
    repositoryClass: WellCommerce\Bundle\CatalogBundle\Repository\VariantOptionRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToOne:
        variant:
            targetEntity: WellCommerce\Bundle\CatalogBundle\Entity\Variant
            fetch: LAZY
            inversedBy: options
            joinColumns:
                variant_id:
                    referencedColumnName: id
                    onDelete: CASCADE
        attribute:
            targetEntity: WellCommerce\Bundle\CatalogBundle\Entity\Attribute
            fetch: LAZY
            joinColumns:
                attribute_id:
                    referencedColumnName: id
                    onDelete: CASCADE
        attributeValue:
            targetEntity: WellCommerce\Bundle\CatalogBundle\Entity\AttributeValue
            fetch: LAZY
            joinColumns:
                attribute_value_id:
                    referencedColumnName: id
                    onDelete: CASCADE

