
services:
    sales_report.provider:
        class: WellCommerce\Bundle\OrderBundle\Provider\SalesReportProvider
        arguments: ['@order.repository']
        calls:
            - [setContainer, ['@service_container']]

    twig.extension.report:
        class: WellCommerce\Bundle\OrderBundle\Twig\Extension\ReportExtension
        arguments: ['WellCommerceOrderBundle:Admin/SalesReport:sales_report.html.twig', '@sales_report.provider', '@request.helper']
        tags:
            - { name: twig.extension }
