WellCommerce\Bundle\OrderBundle\Entity\OrderStatus:
    fields:
        id:
            groups:
                - default
                - order_status
        enabled:
            groups:
                - default
                - order_status
        createdAt:
            groups: {  }
        updatedAt:
            groups: {  }
    associations:
        orderStatusGroup:
            groups:
                - order_status
        createdBy:
            groups:
                - order_status
        updatedBy:
            groups:
                - order_status
        deletedBy:
            groups:
                - order_status
        translations:
            groups:
                - order_status
    callbacks: {  }
