WellCommerce\Bundle\OrderBundle\Entity\Order:
    fields:
        id:
            groups:
                - default
                - order
        confirmed:
            groups:
                - default
                - order
        number:
            groups:
                - default
                - order
        sessionId:
            groups:
                - default
                - order
        currency:
            groups:
                - default
                - order
        currencyRate:
            groups:
                - default
                - order
        comment:
            groups:
                - default
                - order
        productTotal:
            groups:
                - default
                - order
        summary:
            groups:
                - default
                - order
        billingAddress:
            groups:
                - default
                - order
        shippingAddress:
            groups:
                - default
                - order
        contactDetails:
            groups:
                - default
                - order
        createdAt:
            groups: {  }
        updatedAt:
            groups: {  }
    associations:
        products:
            groups:
                - order
        orderStatusHistory:
            groups:
                - order
        modifiers:
            groups:
                - order
        payments:
            groups:
                - order
        coupon:
            groups:
                - order
        client:
            groups:
                - order
        paymentMethod:
            groups:
                - order
        currentStatus:
            groups:
                - order
        shippingMethod:
            groups:
                - order
        shop:
            groups:
                - order
    callbacks: {  }
