# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

well_commerce_api:
    request_handler:
        wishlist:
            manager: wishlist.manager
    serialization:
        WellCommerce\Bundle\WishlistBundle\Entity\Wishlist:
            mapping: "@WellCommerceWishlistBundle/Resources/config/serialization/Wishlist.yml"
