# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

services:
    twig.extension.locale:
        class: WellCommerce\Bundle\AppBundle\Twig\LocaleExtension
        tags:
            - { name: twig.extension }
        arguments: ['@locale.dataset.front']

    locale.controller.front:
        class: WellCommerce\Bundle\AppBundle\Controller\Front\LocaleController
        arguments: ['@locale.manager']
        calls:
            - [setContainer, ['@service_container']]

    locale.subscriber:
        class: WellCommerce\Bundle\AppBundle\EventListener\LocaleSubscriber
        tags:
            - { name: kernel.event_subscriber }
        calls:
            - [setContainer, ['@service_container']]

    form.translation.data_transformer:
        class: WellCommerce\Bundle\AppBundle\Form\DataTransformer\TranslationTransformer
        tags:
            - { name: form.data_transformer, alias: translation }
        arguments: ['@doctrine.helper']
        shared: false
