# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

front.sitemap.index:
    path: /{_locale}/sitemap
    defaults:
        _controller: 'sitemap.controller.front:indexAction'
        _locale: '%locale%'
