# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

WellCommerce\Bundle\AppBundle\Entity\ClientGroup:
    type: entity
    table: client_group
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        discount:
            type: string
            nullable: true
    embedded:
        minimumOrderAmount:
            class: WellCommerce\Bundle\AppBundle\Entity\MinimumOrderAmount
            columnPrefix: minimum_order_amount_
    oneToMany:
        clients:
            targetEntity: WellCommerce\Bundle\AppBundle\Entity\Client
            fetch: LAZY
            mappedBy: clientGroup
            inversedBy: null
            orphanRemoval: false
            orderBy: null
    manyToMany:
        pages:
            targetEntity: WellCommerce\Bundle\CmsBundle\Entity\Page
            fetch: LAZY
            mappedBy: clientGroups
