WellCommerce\Bundle\AppBundle\Entity\Company:
    type: entity
    table: company
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            nullable: false
        shortName:
            type: string
            length: 255
            nullable: false
            column: short_name
        line1:
            type: string
            length: 255
            nullable: true
        line2:
            type: string
            length: 255
            nullable: true
        postalCode:
            type: string
            length: 255
            nullable: true
            column: postal_code
        state:
            type: string
            length: 255
            nullable: true
        city:
            type: string
            length: 255
            nullable: true
        country:
            type: string
            length: 3
            nullable: true
