WellCommerce\Bundle\AppBundle\Entity\Dictionary:
    type: entity
    table: dictionary
    uniqueConstraints:
        dictionary_unique_idx:
            columns:
                - identifier
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        identifier:
            type: string
            length: 255
            nullable: false
