WellCommerce\Bundle\CmsBundle\Entity\NewsRoute:
    type: entity
    cache:
        usage: NONSTRICT_READ_WRITE
    table: route_news
    manyToOne:
        identifier:
            targetEntity: WellCommerce\Bundle\CmsBundle\Entity\News
            fetch: LAZY
            joinColumns:
                foreign_id:
                    referencedColumnName: id
                    onDelete: CASCADE
