# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

admin.contact.index:
    path: /index
    defaults:
        _controller: 'contact.controller.admin:indexAction'
    options:
        require_admin_permission: contact.index

admin.contact.grid:
    path: /grid
    condition: "request.isXmlHttpRequest()"
    defaults:
        _controller: 'contact.controller.admin:gridAction'
    options:
        expose: true
        require_admin_permission: contact.index

admin.contact.add:
    path: /add
    defaults:
        _controller: 'contact.controller.admin:addAction'
    options:
        require_admin_permission: contact.add

admin.contact.edit:
    path: '/edit/{id}'
    defaults:
        _controller: 'contact.controller.admin:editAction'
    options:
        expose: true
        require_admin_permission: contact.edit

admin.contact.delete:
    path: '/delete/{id}'
    defaults:
        _controller: 'contact.controller.admin:deleteAction'
    options:
        expose: true
        require_admin_permission: contact.delete

admin.contact.delete_group:
    path: '/delete_group'
    defaults:
        _controller: 'contact.controller.admin:deleteGroupAction'
    options:
        expose: true
        require_admin_permission: contact.delete
