# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

admin.review.index:
    path: /index
    defaults:
        _controller: 'review.controller.admin:indexAction'
    options:
        require_admin_permission: review.index

admin.review.grid:
    path: /grid
    condition: "request.isXmlHttpRequest()"
    defaults:
        _controller: 'review.controller.admin:gridAction'
    options:
        expose: true
        require_admin_permission: review.index

admin.review.edit:
    path: '/edit/{id}'
    defaults:
        _controller: 'review.controller.admin:editAction'
    options:
        expose: true
        require_admin_permission: review.edit

admin.review.delete:
    path: '/delete/{id}'
    defaults:
        _controller: 'review.controller.admin:deleteAction'
    options:
        expose: true
        require_admin_permission: review.delete

admin.review.delete_group:
    path: '/delete_group'
    defaults:
        _controller: 'review.controller.admin:deleteGroupAction'
    options:
        expose: true
        require_admin_permission: review.delete

admin.review.enable:
    path: '/enable/{id}'
    defaults:
        _controller: 'review.controller.admin:enableAction'
    options:
        expose: true
        require_admin_permission: review.edit

admin.review.disable:
    path: '/disable/{id}'
    defaults:
        _controller: 'review.controller.admin:disableAction'
    options:
        expose: true
        require_admin_permission: review.edit