WellCommerce\Bundle\OrderBundle\Entity\OrderStatusGroup:
    fields:
        id:
            groups:
                - default
                - order_status_group
        createdAt:
            groups: {  }
        updatedAt:
            groups: {  }
    associations:
        createdBy:
            groups:
                - order_status_group
        updatedBy:
            groups:
                - order_status_group
        deletedBy:
            groups:
                - order_status_group
        translations:
            groups:
                - order_status_group
    callbacks: {  }
