WellCommerce\Bundle\OrderBundle\Entity\OrderProduct:
    fields:
        id:
            groups:
                - default
                - order_product
        quantity:
            groups:
                - default
                - order_product
        weight:
            groups:
                - default
                - order_product
        options:
            groups:
                - default
                - order_product
        buyPrice:
            groups:
                - default
                - order_product
        sellPrice:
            groups:
                - default
                - order_product
    associations:
        product:
            groups:
                - order_product
                - default
        variant:
            groups:
                - order_product
                - default
