WellCommerce\Bundle\OrderBundle\Entity\OrderModifier:
    type: entity
    table: order_modifier
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            nullable: false
        description:
            type: string
            nullable: false
        subtraction:
            type: boolean
            nullable: false
            options:
                default: false
        netAmount:
            type: decimal
            scale: 2
            nullable: false
            precision: 15
            column: net_amount
        grossAmount:
            type: decimal
            scale: 2
            nullable: false
            precision: 15
            column: gross_amount
        taxAmount:
            type: decimal
            scale: 2
            nullable: false
            precision: 15
            column: tax_amount
        currency:
            type: string
            length: 16
            nullable: false
            column: currency
    manyToOne:
        order:
            targetEntity: WellCommerce\Bundle\OrderBundle\Entity\Order
            fetch: LAZY
            inversedBy: modifiers
            joinColumns:
                order_id:
                    referencedColumnName: id
                    onDelete: CASCADE
