WellCommerce\Bundle\CmsBundle\Entity\NewsCategoryTranslation:
    type: entity
    table: news_category_translation
    fields:
        name:
            type: string
            length: 255
            nullable: false
