# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

admin.attribute_value.index:
    path: /index
    defaults:
        _controller: 'attribute_value.controller.admin:indexAction'
    options:
        require_admin_permission: attribute_value.index

admin.attribute_value.grid:
    path: /grid
    condition: "request.isXmlHttpRequest()"
    defaults:
        _controller: 'attribute_value.controller.admin:gridAction'
    options:
        expose: true
        require_admin_permission: attribute_value.index

admin.attribute_value.add:
    path: /add
    defaults:
        _controller: 'attribute_value.controller.admin:addAction'
    options:
        require_admin_permission: attribute_value.add

admin.attribute_value.edit:
    path: '/edit/{id}'
    defaults:
        _controller: 'attribute_value.controller.admin:editAction'
    options:
        expose: true
        require_admin_permission: attribute_value.edit

admin.attribute_value.delete:
    path: '/delete/{id}'
    defaults:
        _controller: 'attribute_value.controller.admin:deleteAction'
    options:
        expose: true
        require_admin_permission: attribute_value.delete

admin.attribute_value.delete_group:
    path: '/delete_group'
    defaults:
        _controller: 'attribute_value.controller.admin:deleteGroupAction'
    options:
        expose: true
        require_admin_permission: attribute_value.delete

admin.attribute_value.ajax.index:
    path: /ajax/index
    defaults:
        _controller: 'attribute_value.controller.admin:ajaxIndexAction'
    options:
        expose: true
        require_admin_permission: attribute_value.index

admin.attribute_value.ajax.add:
    path: /ajax/add
    defaults:
        _controller: 'attribute_value.controller.admin:ajaxAddAction'
    options:
        expose: true
        require_admin_permission: attribute_value.add

admin.attribute_value.ajax.edit:
    path: '/ajax/edit/{id}'
    defaults:
        _controller: 'attribute_value.controller.admin:ajaxEditAction'
    options:
        expose: true
        require_admin_permission: attribute_value.edit

admin.attribute_value.ajax.delete:
    path: '/ajax/delete/{id}'
    defaults:
        _controller: 'attribute_value.controller.admin:ajaxDeleteAction'
    options:
        expose: true
        require_admin_permission: attribute_value.delete
