# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

admin.client.index:
    path: /index
    defaults:
        _controller: 'client.controller.admin:indexAction'
    options:
        require_admin_permission: client.index

admin.client.grid:
    path: /grid
    condition: "request.isXmlHttpRequest()"
    defaults:
        _controller: 'client.controller.admin:gridAction'
    options:
        expose: true
        require_admin_permission: client.index

admin.client.add:
    path: /add
    defaults:
        _controller: 'client.controller.admin:addAction'
    options:
        require_admin_permission: client.add

admin.client.edit:
    path: '/edit/{id}'
    defaults:
        _controller: 'client.controller.admin:editAction'
    options:
        expose: true
        require_admin_permission: client.edit

admin.client.delete:
    path: '/delete/{id}'
    defaults:
        _controller: 'client.controller.admin:deleteAction'
    options:
        expose: true
        require_admin_permission: client.delete

admin.client.delete_group:
    path: '/delete_group'
    defaults:
        _controller: 'client.controller.admin:deleteGroupAction'
    options:
        expose: true
        require_admin_permission: client.delete

admin.client.details:
    path: '/details/{id}'
    defaults:
        _controller: 'client.controller.admin:detailsAction'
    options:
        expose: true
        require_admin_permission: client.edit
