# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

WellCommerce\Bundle\InvoiceBundle\Entity\InvoiceItem:
    type: entity
    table: invoice_item
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        description:
            type: text
        netAmount:
            type: decimal
            scale: 2
            nullable: false
            precision: 15
            column: net_amount
        grossAmount:
            type: decimal
            scale: 2
            nullable: false
            precision: 15
            column: gross_amount
        taxAmount:
            type: decimal
            scale: 2
            nullable: false
            precision: 15
            column: tax_amount
        taxRate:
            type: decimal
            scale: 2
            nullable: false
            precision: 15
            column: tax_rate
        currency:
            type: string
            length: 16
            nullable: false
            column: currency
        quantity:
            type: integer
            nullable: false
    manyToOne:
        invoice:
            targetEntity: WellCommerce\Bundle\InvoiceBundle\Entity\Invoice
            fetch: LAZY
            inversedBy: items
            joinColumns:
                invoice_id:
                    referencedColumnName: id
                    onDelete: CASCADE
