# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

well_commerce_app:
    locale_copier:
        entities:
            WellCommerce\Bundle\FeatureBundle\Entity\FeatureTranslation:
                properties:
                    - name
            WellCommerce\Bundle\FeatureBundle\Entity\FeatureGroupTranslation:
                properties:
                    - name
            WellCommerce\Bundle\FeatureBundle\Entity\FeatureSetTranslation:
                properties:
                    - name
