# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

WellCommerce\Bundle\CatalogBundle\Entity\AttributeValue:
    fields:
        id:
            groups:
                - default
                - attribute_value
    associations:
        translations:
            groups:
                - default
                - attribute_value
