# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

admin.attribute.index:
    path: /admin/attribute/index
    defaults:
        _controller: 'attribute.controller.admin:indexAction'
    options:
        require_admin_permission: attribute.index

admin.attribute.grid:
    path: /admin/attribute/grid
    condition: "request.isXmlHttpRequest()"
    defaults:
        _controller: 'attribute.controller.admin:gridAction'
    options:
        expose: true
        require_admin_permission: attribute.index

admin.attribute.add:
    path: /admin/attribute/add
    defaults:
        _controller: 'attribute.controller.admin:addAction'
    options:
        require_admin_permission: attribute.add

admin.attribute.edit:
    path: '/admin/attribute/edit/{id}'
    defaults:
        _controller: 'attribute.controller.admin:editAction'
    options:
        expose: true
        require_admin_permission: attribute.edit

admin.attribute.delete:
    path: '/admin/attribute/delete/{id}'
    defaults:
        _controller: 'attribute.controller.admin:deleteAction'
    options:
        expose: true
        require_admin_permission: attribute.delete

admin.attribute.delete_group:
    path: '/admin/attribute/delete_group'
    defaults:
        _controller: 'attribute.controller.admin:deleteGroupAction'
    options:
        expose: true
        require_admin_permission: attribute.delete

admin.attribute.ajax.index:
    path: /admin/attribute/ajax/index
    defaults:
        _controller: 'attribute.controller.admin:ajaxIndexAction'
    options:
        expose: true
        require_admin_permission: attribute.index

admin.attribute.ajax.add:
    path: /admin/attribute/ajax/add
    defaults:
        _controller: 'attribute.controller.admin:ajaxAddAction'
    options:
        expose: true
        require_admin_permission: attribute.add

admin.attribute.ajax.generate:
    path: /admin/attribute/ajax/generate
    defaults:
        _controller: 'attribute.controller.admin:ajaxGenerateCartesianAction'
    options:
        expose: true
        require_admin_permission: attribute.add
