# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

WellCommerce\Bundle\AppBundle\Entity\ClientShippingAddress:
    fields:
        firstName:
            groups:
                - default
                - client_shipping_address
        lastName:
            groups:
                - default
                - client_shipping_address
        line1:
            groups:
                - default
                - client_shipping_address
        line2:
            groups:
                - default
                - client_shipping_address
        postalCode:
            groups:
                - default
                - client_shipping_address
        state:
            groups:
                - default
                - client_shipping_address
        city:
            groups:
                - default
                - client_shipping_address
        country:
            groups:
                - default
                - client_shipping_address
        copyBillingAddress:
            groups:
                - default
                - client_shipping_address
    associations: {  }
    callbacks: {  }
