WellCommerce\Bundle\AppBundle\Entity\TaxTranslation:
    fields:
        name:
            groups:
                - default
                - tax_translation
        locale:
            groups:
                - default
                - tax_translation
        id:
            groups:
                - default
                - tax_translation
    associations:
        translatable:
            groups:
                - tax_translation
    callbacks: {  }
