# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

admin.news_category.index:
    path: /index
    defaults:
        _controller: 'news_category.controller.admin:indexAction'
    options:
        require_admin_permission: news_category.index

admin.news_category.grid:
    path: /grid
    condition: "request.isXmlHttpRequest()"
    defaults:
        _controller: 'news_category.controller.admin:gridAction'
    options:
        expose: true
        require_admin_permission: news_category.index

admin.news_category.add:
    path: /add
    defaults:
        _controller: 'news_category.controller.admin:addAction'
    options:
        require_admin_permission: news_category.add

admin.news_category.edit:
    path: '/edit/{id}'
    defaults:
        _controller: 'news_category.controller.admin:editAction'
    options:
        expose: true
        require_admin_permission: news_category.edit

admin.news_category.delete:
    path: '/delete/{id}'
    defaults:
        _controller: 'news_category.controller.admin:deleteAction'
    options:
        expose: true
        require_admin_permission: news_category.delete

admin.news_category.delete_group:
    path: '/delete_group'
    defaults:
        _controller: 'news_category.controller.admin:deleteGroupAction'
    options:
        expose: true
        require_admin_permission: news_category.delete
