# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

WellCommerce\Bundle\CatalogBundle\Entity\CategoryTranslation:
    fields:
        name:
            groups:
                - default
                - category_translation
        shortDescription:
            groups:
                - default
                - category_translation
        description:
            groups:
                - default
                - category_translation
        slug:
            groups:
                - default
                - category_translation
        meta:
            groups:
                - default
                - category_translation
        locale:
            groups:
                - default
                - category_translation
        id:
            groups:
                - default
                - category_translation
    associations:
        route:
            groups:
                - category_translation
        translatable:
            groups:
                - category_translation
    callbacks: {  }
