WellCommerce\Bundle\CatalogBundle\Entity\ProductRoute:
    fields:
        id:
            groups:
                - default
                - route
        path:
            groups:
                - default
                - route
        locale:
            groups:
                - default
                - route
    associations:
        identifier:
            groups:
                - route
