# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

WellCommerce\Bundle\AppBundle\Entity\Package:
    type: entity
    table: package
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fullName:
            type: string
            length: 255
            unique: true
            nullable: false
            column: full_name
        name:
            type: string
            length: 255
            unique: false
            nullable: false
            precision: 0
        vendor:
            type: string
            length: 255
            unique: false
            nullable: false
        localVersion:
            type: string
            length: 255
            unique: false
            nullable: true
            column: local_version
        remoteVersion:
            type: string
            length: 255
            unique: false
            nullable: true
            column: remote_version
