# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

services:
    doctrine.class_metadata.enhancer_collection:
        class: WellCommerce\Component\DoctrineEnhancer\ClassMetadata\ClassMetadataEnhancerCollection

    doctrine.class_metadata.enhancer_traverser:
        class: WellCommerce\Component\DoctrineEnhancer\ClassMetadata\ClassMetadataEnhancerTraverser
        arguments: ['@doctrine.class_metadata.enhancer_collection']

    doctrine.trait_generator.enhancer_collection:
        class: WellCommerce\Component\DoctrineEnhancer\TraitGenerator\TraitGeneratorEnhancerCollection
        public: false

    doctrine.class_metadata.event_subscriber:
        class: WellCommerce\Bundle\CoreBundle\Doctrine\EventSubscriber\ClassMetadataEventSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        arguments: ['@doctrine.class_metadata.enhancer_traverser']

    doctrine.timestampable.event_subscriber:
        class: WellCommerce\Bundle\CoreBundle\Doctrine\EventSubscriber\TimestampableSubscriber
        tags:
            - { name: doctrine.event_subscriber }

    doctrine.sortable.event_subscriber:
        class: WellCommerce\Bundle\CoreBundle\Doctrine\EventSubscriber\SortableSubscriber
        tags:
            - { name: doctrine.event_subscriber }

    doctrine.enableable.event_subscriber:
        class: WellCommerce\Bundle\CoreBundle\Doctrine\EventSubscriber\EnableableSubscriber
        tags:
            - { name: doctrine.event_subscriber }

    doctrine.cache_invalidator.event_subscriber:
        class: WellCommerce\Bundle\CoreBundle\Doctrine\EventSubscriber\CacheInvalidatorSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        arguments: ['@cache']

    doctrine.helper:
        class: WellCommerce\Bundle\CoreBundle\Helper\Doctrine\DoctrineHelper
        arguments: ['@doctrine']

    doctrine.enhance.command:
        class: WellCommerce\Bundle\CoreBundle\Command\Doctrine\EnhanceCommand
        arguments: ['@process.helper', '@doctrine.trait_generator.enhancer_collection']
        tags:
            - { name: console.command }
