# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

WellCommerce\Bundle\FeatureBundle\Entity\FeatureGroup:
    type: entity
    table: feature_group
    cache:
        usage: NONSTRICT_READ_WRITE
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToMany:
        sets:
            targetEntity: WellCommerce\Bundle\FeatureBundle\Entity\FeatureSet
            fetch: LAZY
            mappedBy: groups
            cascade:
                - persist
        features:
            targetEntity: WellCommerce\Bundle\FeatureBundle\Entity\Feature
            fetch: LAZY
            inversedBy: groups
            joinTable:
                name: feature_group_feature
                joinColumns:
                    -
                        name: feature_group_id
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    -
                        name: feature_id
                        referencedColumnName: id
                        onDelete: CASCADE
            cascade:
                - persist
