# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

WellCommerce\Bundle\FeatureBundle\Entity\FeatureSet:
    type: entity
    table: feature_set
    cache:
        usage: NONSTRICT_READ_WRITE
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToMany:
        groups:
            targetEntity: WellCommerce\Bundle\FeatureBundle\Entity\FeatureGroup
            fetch: LAZY
            inversedBy: sets
            joinTable:
                name: feature_set_group
                joinColumns:
                    -
                        name: feature_set_id
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    -
                        name: feature_group_id
                        referencedColumnName: id
                        onDelete: CASCADE
            cascade:
                - persist
